name: Merge genx_test into geny_test

on:
  workflow_dispatch

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout geny_test branch
        uses: actions/checkout@v4
        with:
          ref: geny_test
      - name: Merge genx_test into geny_test
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git fetch origin genx_test
          git merge origin/genx_test --no-edit --allow-unrelated-histories
          git push origin geny_test
